### ISSUE TITLE
[Automatismo] Obtener temperatura para encender el A/A

### ISSUE THREAD

**Issue by JMVS** [mool/home-assistant-bgh-smart#1]
Hola, primero que nada, muchas gracias por crear esta integración para Home Assistant. Hacía tiempo estaba buscando algo similar.
Por otro lado, quería saber si había forma de utilizar el valor de "current_temperature" en un automatismo para encender el aire acondicionado basado (entre otras cosas) en la temperatura actual.
Gracias.
Jose

**Comment by mool** [comment]
Hola @JMVS, se pueden crear automatizaciones usando el valor de `current_temperature`, para eso deberias usar template triggers https://www.home-assistant.io/docs/automation/trigger/#template-trigger
Y en caso de querer disparar acciones en la entidad, podes usar cualquiera de los servicios de `climate` https://www.home-assistant.io/integrations/climate/

**Comment by JMVS** [comment]
Para futura referencia, se puede crear un sensor con la temperatura de la siguiente manera:
![imagen](https://user-images.githubusercontent.com/7751148/87487974-8539ec00-c615-11ea-9149-f9245b21a4db.png)

**Agregar a configuration.yaml:**
```
sensor:
    sensors:
      #Poner un nombre único para el sensor
      temp_aire_acondicionado:
        #Poner un nombre a mostrar en el sensor
        friendly_name: "Temperatura: Aire Acondicionado"
        #Unidad de medida
        unit_of_measurement: '°C'
        #Reemplazar "climate.aa_aire_acondicionado" por el nombre de la entidad como figura en Home Assistant
        value_template: "{{ state_attr('climate.aa_aire_acondicionado', 'current_temperature') }}"
```
**Guardar y reiniciar.**
